# Generated by Django 2.0.4 on 2018-05-14 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extenden_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.Extenden_User')),
            ],
            options={
                'db_table': 'ideas',
            },
        ),
        migrations.CreateModel(
            name='IdeaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.Ideas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.Extenden_User')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.Ideas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.Extenden_User')),
            ],
            options={
                'db_table': 'views',
            },
        ),
        migrations.AddField(
            model_name='ideas',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.IdeaStatus'),
        ),
        migrations.AddField(
            model_name='extenden_user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproj.Role'),
        ),
        migrations.AddField(
            model_name='extenden_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
