# Generated by Django 2.0.4 on 2018-05-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testproj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Extended User',
                'verbose_name_plural': 'Extended Users',
                'db_table': 'extendeduser',
            },
        ),
        migrations.RemoveField(
            model_name='extenden_user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='extenden_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='views',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='views',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ideas',
            options={'verbose_name': 'Ideas', 'verbose_name_plural': 'Ideas'},
        ),
        migrations.AlterModelOptions(
            name='ideastatus',
            options={'verbose_name': 'Idea Status', 'verbose_name_plural': 'Idea Statuses'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Roles', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='status',
            new_name='role',
        ),
        migrations.AddField(
            model_name='ideas',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='testproj.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tostatus', to='testproj.IdeaStatus'),
        ),
        migrations.AlterModelTable(
            name='ideastatus',
            table='ideastatus',
        ),
        migrations.DeleteModel(
            name='Extenden_User',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Views',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torole', related_query_name='', to='testproj.Role'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
