# Generated by Django 2.0.4 on 2018-05-19 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0002_auto_20180517_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideastatus',
            name='status',
            field=models.CharField(default='Just created', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='User', max_length=255, unique=True),
        ),
    ]
