# Generated by Django 2.0.4 on 2018-05-20 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0002_auto_20180517_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='moderator',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to='testproj.ExtendedUser'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='views',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_id', related_query_name='', to='testproj.Role'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='testproj.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_id', to='testproj.IdeaStatus'),
        ),
        migrations.AlterField(
            model_name='ideastatus',
            name='status',
            field=models.CharField(default='Just created', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='User', max_length=255, unique=True),
        ),
    ]
