# Generated by Django 2.0.4 on 2018-05-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0003_auto_20180520_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='moderator',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to='testproj.ExtendedUser'),
        ),
    ]
