# Generated by Django 2.0.4 on 2018-05-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0004_auto_20180520_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='moderator',
        ),
    ]
