# Generated by Django 2.0.4 on 2018-05-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0005_remove_ideas_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='moderator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to='testproj.ExtendedUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideas',
            name='views',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
