# Generated by Django 2.0.4 on 2018-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0006_auto_20180520_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='moderator',
        ),
    ]
