DROP DATABASE IF EXISTS `dbtest`;
CREATE DATABASE `dbtest` DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE `dbtest`;
GRANT ALL PRIVILEGES ON *.* TO 'sluser'@'localhost' IDENTIFIED BY 'jDW72Gsvkk8s'

WITH GRANT OPTION;
FLUSH PRIVILEGES;
